name: .NET Build

on:
  push:
    branches: [ "v11/dev" ]
  pull_request:
    branches: [ "v11/dev" ]

jobs:

  build:
    runs-on: windows-latest 

    env:
      Configuration: Release
      Solution_File: uSync.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build ${{ Solution_File }} --no-restore -c ${{ Configuration }}
      
  
